### PR TITLE
Fix local installation instruction path

### PR DESCRIPTION
**Pull request by alexandervantrijffel**

### CODE REVIEW

**Comment by ccojocar** [comment]
@alexandervantrijffel Thanks for this update but it is not required. Please check the https://github.com/securego/gosec/pull/532 for more details.

**Comment by alexandervantrijffel** [comment]
@ccojocar this command as currently described on the readme fails:

go get github.com/securego/gosec/v2/cmd/gosec

with error:

cannot find package "github.com/securego/gosec/v2/cmd/gosec" in any of

So in my humble opinion it would be helpful to change the path.

**Comment by ccojocar** [comment]
@alexandervantrijffel Which go version are you using? Do you have the go modules enabled?

I've just run it on my side:
```
$ go get -u github.com/securego/gosec/v2/cmd/gosec
go: downloading github.com/securego/gosec/v2 v2.5.0
go: found github.com/securego/gosec/v2/cmd/gosec in github.com/securego/gosec/v2 v2.5.0
go: golang.org/x/xerrors upgrade => v0.0.0-20200804184101-5ec99f83aff1
go: gopkg.in/yaml.v2 upgrade => v2.4.0
go: github.com/gookit/color upgrade => v1.3.2
go: golang.org/x/mod upgrade => v0.4.0
go: golang.org/x/tools upgrade => v0.0.0-20201202100533-7534955ac86b
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading github.com/gookit/color v1.3.2
go: downloading golang.org/x/tools v0.0.0-20201202100533-7534955ac86b
go: downloading golang.org/x/mod v0.4.0
```

```
go version
go version go1.15.4 darwin/amd64
```

**Comment by alexandervantrijffel** [comment]
I do have version 1.15.5 installed with support for go modules:

```
❯ go version
go version go1.15.5 linux/amd64
❯ go get -u github.com/securego/gosec/v2/cmd/gosec
cannot find package "github.com/securego/gosec/v2/cmd/gosec" in any of:
	/usr/local/go/src/github.com/securego/gosec/v2/cmd/gosec (from $GOROOT)
	/data/dev/go/src/github.com/securego/gosec/v2/cmd/gosec (from $GOPATH)      
```

**Comment by ccojocar** [comment]
I tried again with Go 1.15.5 and also wiped everything locally. It seems to work for me:
```
go get -u github.com/securego/gosec/v2/cmd/gosec
go: found github.com/securego/gosec/v2/cmd/gosec in github.com/securego/gosec/v2 v2.5.0
go: gopkg.in/yaml.v2 upgrade => v2.4.0
go: github.com/gookit/color upgrade => v1.3.2
go: golang.org/x/mod upgrade => v0.4.0
go: golang.org/x/tools upgrade => v0.0.0-20201202100533-7534955ac86b
go: golang.org/x/xerrors upgrade => v0.0.0-20200804184101-5ec99f83aff1
```

There are my environment variables:
```
GO111MODULE=on
GOROOT=/Users/cosmin/.gvm/gos/go1.15.5
GOPATH=/Users/cosmin/go
```

It might be something wrong with your Go installation. 

Also note that when not providing the `v2` into the path, it will pick the latest 1.x version instead of 2.x.

**Pull request closed without merging**
