### PR TITLE
Add support to exclude arbitrary folders from scanning

### LINKED ISSUE #342: Ignore abitrary directory
### Summary 
By default gosec ignores files in the 'tests' directory. However my project uses the name 'test' to store tests. It would be nice if we could specify arbitrary directory name to be ignored.

### Steps to reproduce the behavior
Scan a project recursively with a 'test' folder.

### gosec version
commit 4b59c948083cd711b6a8aac8f32721b164899f57

### Go version (output of 'go version')
go version go1.12.7 linux/amd64

### PR DESCRIPTION
**Pull request by ccojocar**
fixes #342

### CODE REVIEW

**Comment by ccojocar** [comment]
This is a simple approach to exclude an entire folder. A path is excluded from scanning if one segment of the path matches the regex.

We can improve it in case there will be confusion.

**Comment by gcmurphy** [comment]
Ok I think that's better. Previously I think we tried matching whole regex.

**Comment by arangamani** [comment]
Is there an ETA on seeing this change on a releasee tag?

**Comment by ccojocar** [comment]
I hope we will cut soon a release.

**Pull request merged**
