### PR TITLE
Feature: Rule G401 split into two different rules

### LINKED ISSUE #1158: Rule G401 covers multiple different CWEs.
### Summary 
Rule G401 covers multiple CWEs inaccurately.

### Steps to reproduce the behavior
None.

### gosec version
Gosec compiled from main branch.
Last committed hash: 2ae137abcf405533ad6e549e9363e58e4f6e8b7d

### Go version (output of 'go version')
go1.22.4 linux/amd64

### Operating system / Environment
Linux

### Expected behavior
Currently, rule G401 detects the usage of outdated encryption and hashing algorithms.
Personally, I would categorize hashing algorithms with [CWE-328](https://cwe.mitre.org/data/definitions/328.html), and encryption algorithms with [CWE-327](https://cwe.mitre.org/data/definitions/327.html)

### Actual behavior
Usage of MD5 and SHA1 is detected as [CWE-326](https://cwe.mitre.org/data/definitions/326.html).
Which is not informative enough.

### PR DESCRIPTION
**Pull request by expp121**
Currently, rule G401 is used both for encryption and hashing algorithms, this might result in wrong categorization of a weakness.

This pull request aims to solve that problem, by splitting the rule into two separate ones(G401, G405).

Rule G401 is now responsible for only checking hashing algorithms such as MD5 and SHA1. Code containing those algorithms is flagged with CWE-328.

And the new rule G405 is responsible for checking encryption algorithms such as DES and RC4. And it flags code containing them with CWE-327.

closes #1158

### CODE REVIEW

**Review by ccojocar — APPROVED** [review]
Thanks for splitting this up.

**Comment by ccojocar** [comment]
@expp121 There seems to be some lint warnings, please could you fix them. I think the test file needs to be formatted. Thanks

**Comment by expp121** [comment]
Thank you for the advice @ccojocar! I hope I've fixed (quite new to github actions) the issue with the most recent commit.

I would also like to ask whether the [analyzer_test.go](https://github.com/securego/gosec/blob/33b573b8008cf27888e2d4eaa1cb59cd66974282/analyzer_test.go) file, should contain a license of some sort?

**Comment by ccojocar** [comment]
> I would also like to ask whether the [analyzer_test.go](https://github.com/securego/gosec/blob/33b573b8008cf27888e2d4eaa1cb59cd66974282/analyzer_test.go) file, should contain a license of some sort?

@expp121 Yeah, it should have the same Apache license header file like the other files with an updated year. Please could you add it? Thanks a lot

**Review by ccojocar — APPROVED** [review]

**Comment by ccojocar** [comment]
@expp121 I'll merge this. You can add the license header in a separate PR. Thanks

**Pull request merged**
