### PR TITLE
Add G307 sample code.

### PR DESCRIPTION
**Pull request by elgohr**
fixes https://github.com/securego/gosec/issues/657

The sample should reflect a defered close that leads to data loss.
Due to IDE auto-complete people tend to at least log errors, but not really care about handling.

To my point of view this could be fixed by seeing a deferred `f.Close()`, without a correspondig `f.Sync()`, generally as a bad pattern.

### CODE REVIEW

**Review by ccojocar — APPROVED** [review]

**Comment by ccojocar** [comment]
@elgohr It seems that the test is failing. Could you please have a look? Thanks!

**Comment by elgohr** [comment]
As said, I wrote the test. Do you want to discuss on the implementation or should I just give it a try?

**Comment by ccojocar** [comment]
We can discuss on slack if you have questions. Otherwise you can give it a try, and I will review it when is ready.

**Comment by elgohr** [comment]
I took a few tries and all ended up in turning G307 around and putting os.File in the center, instead of defer.
I don't think that's a good thing for the future of that rule. At the moment I don't see an easy to read solution for this, if we keep the structure as is... Do you have an idea?

**Comment by ccojocar** [comment]
@elgohr Could you share what you have so far? I can have a look at your current implementation. Thanks

**Comment by elgohr** [comment]
So this would be an idea for implementing - without turning the whole thing around

**Review by ccojocar — COMMENTED** [review]
It looks good!

**Comment by ccojocar** [comment]
It seems that there are some lint warnings to fix. Could you please have a look? Thanks

**Comment by elgohr** [comment]
So I fixed the linting and added an example that I would like to discuss.

https://github.com/elgohr/gosec/commit/b1c5f2cd89c5efd979872085f80be5913198b1a8#diff-ac25ed6050bbf7e77dd739a9fc894d1ed3f2ab52dbf6a9b2b582577a91da1204R2061
This should not return an error, as it's savely synced.
Nevertheless it can't be tested, as the `Match` only gets defers...

**Comment by ccojocar** [comment]
> So I fixed the linting and added an example that I would like to discuss.

Thanks for fixing the linting warnings. 

> This should not return an error, as it's savely synced.
Nevertheless it can't be tested, as the Match only gets defers..

I think the AST tree has to be traversed further into the defer statement in order to verify if the error is checked. `gosec` doesn't really have call graph tracing or taint analysis support. Do you want to work on this specific improvement for defer statement?

**Comment by ccojocar** [comment]
The test is failing as you mentioned above. You can also remove this test in order for us to merge the pull request and contribute the improvement in a follow up pull request. What do you think?

**Comment by elgohr** [comment]
So I rebased to upstream (that's why force push) and removed the failing test (for now).

**Comment by ccojocar** [comment]
Thanks for following! I removed some IDEA related files which I think you committed accidentally.

**Pull request merged**
