### PR TITLE
Integrate the goreleaser tool

### LINKED ISSUE #194: Look at integrating https://goreleaser.com/
In addition to the recent build changes it might be worth looking at integrating with goreleaser

### PR DESCRIPTION
**Pull request by ccojocar**
Fixes #194

### CODE REVIEW

**Comment by gcmurphy** [comment]
@cosmincojocar  I'm thinking of just renaming the github org to something shorter and keeping the name of 'gas'.  maybe changing the acronym to mean 'Go Application Security' or something similar as per #85 

Will it be better to do this before / after merging the goreleaser work?

**Comment by cosmincojocar** [comment]
@gcmurphy I think, it's a good idea to do the renaming before publishing any release. Do you have any specific name in mind? `gosec` sounds good to me. It fits the current purpose of the tool and it's inline with the naming conversion used by other go tools. 

I am also fine to keep the current name and just rename the organization to `gas`.

**Comment by ccojocar** [comment]
@gcmurphy Do you intend to merge this PR?

**Comment by gcmurphy** [comment]
I've been meaning to do the rename (at least to the github org) first, but haven't had much time to devote to this project due to other life commitments. I'll add you as a core dev to the project so things are less blocked on my approvals.

**Comment by ccojocar** [comment]
Thanks! I joined the GitHub org. Which name would you like to use for the GitHub org?

**Comment by gcmurphy** [comment]
@ccojocar renamed to 'securego' as it was available I thought we could create another repo under it securego/guide which is documentation about the logic behind the rules. This is a common request, and we could actually publish it as a git book or something similar and reference urls in the rule output. 

I think we can probably rename the tool if you like as well? Your suggestion was gosec right?

**Comment by ccojocar** [comment]
It sounds great! Yes, my suggestion was `gosec`, which sounds a bit more aligned with other Go tools.

**Comment by ccojocar** [comment]
You can also rename the repo. I'll try to fix the code and documentation.

**Comment by gcmurphy** [comment]
Rename of repo is done. @ccojocar f you can handle the code / docs update from gas -> gosec that'd be great!

**Comment by ccojocar** [comment]
I am closing this in favour of #219.

**Pull request closed without merging**
