### PR TITLE
Handle taxonomies in SARIF format and separate responsibilities

### LINKED ISSUE #587: Support Taxonomies in SARIF
### Summary

GoSec writes the CWE IDs after the rule name.

Example output:

```
{
	"$schema": "https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json",
	"version": "2.1.0",
	"runs": [
		{
			"tool": {
				"driver": {
					"name": "gosec",
					"version": "2.1.0",
					"informationUri": "https://github.com/securego/gosec/",
					"rules": [
						{
							"id": "G404 (CWE-338)",
							"name": "Use of weak random number generator (math/rand instead of crypto/rand)",
							"shortDescription": {
								"text": "Use of weak random number generator (math/rand instead of crypto/rand)"
							},
							"fullDescription": {
								"text": "Use of weak random number generator (math/rand instead of crypto/rand)"
							},
							"help": {
								"text": "Use of weak random number generator (math/rand instead of crypto/rand)\nSeverity: HIGH\nConfidence: MEDIUM\nCWE: https://cwe.mitre.org/data/definitions/338.html"
							},
							"properties": {
								"tags": [
									"CWE-338",
									"HIGH"
								]
							},
							"defaultConfiguration": {
								"level": "error"
							}
						},
```

Using SARIF taxonomies would allow automated tools to work with structured taxonomies instead of parsing the id string to find the CWE number. GoSec has already a GoSec to CWE mapping, therefore implementing CWE as taxonomy in SARIF would require only some changes in the output format. 

SARIF taxonomy support:

- [SARIF 3.19.3 Taxonomies](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317536)
- [Tutorial Example - Taxonomies](https://github.com/microsoft/sarif-tutorials/blob/main/docs/3-Beyond-basics.md#taxonomies)

### Steps to reproduce the behavior

1. Clone: https://github.com/Hardw01f/Vulnerability-goapp
2. Analyze code:

```
cd Vulnerability-goapp
GO111MODULE=on gosec -fmt=sarif ./...
```

### gosec version

```
gosec -version
Version: 2.7.0
Git tag: v2.7.0
Build date: 2021-03-04T09:00:15Z
```

### Go version (output of 'go version')

```
$ go version
go version go1.16 linux/amd64
```

### Operating system / Environment

GNU/Linux -> Docker Ubuntu 20.04

### Expected behavior

The SARIF output of GoSec contains CWE mapping as taxonomy.

### Actual behavior

GoSec outputs rule id's as combination of GoSec id and CWE.

### PR DESCRIPTION
**Pull request by mmorel-35**
I have generated the sarif types with https://github.com/a-h/generate/tree/master/cmd/schema-generate

Fixes  #587 

This also brings some new packages to separate responsibilities : 
* CWE
* SARIF
* Formatter

### CODE REVIEW

**Comment by mmorel-35** [comment]
Hi ! This is ready for view, please have a look and let me know what you think of this.

**Review by ccojocar — APPROVED** [review]
@mmorel-35 Thanks for this great contribution! Can you add please some details in the README file which describes how to generate the types? Thanks again!

**Comment by ccojocar** [comment]
Also please can you squash all the commits in one commit with appropriate message? Thanks!

**Comment by ccojocar** [comment]
@mmorel-35 There are some conflicts after merging the other pull request. Please could you have a look? Thanks!

**Comment by mmorel-35** [comment]
> @mmorel-35 Thanks for this great contribution! Can you add please some details in the README file which describes how to generate the types? Thanks again!

I added a note on this. The method is not really great but it helped me win some time.

> Also please can you squash all the commits in one commit with appropriate message? Thanks!

Can you help me on that, I don't know how to do so 

> @mmorel-35 There are some conflicts after merging the other pull request. Please could you have a look? Thanks!

It's done

**Review by ccojocar — APPROVED** [review]
Thanks for adding the note in the Readme!

**Comment by mmorel-35** [comment]
@Jeeppler, have you challenged the actual file with your requirements ? Maybe you need a release ?

**Comment by Jeeppler** [comment]
@mmorel-35 A release would be awesome.

**Comment by Jeeppler** [comment]
@mmorel-35 your implementation is really good. Thanks a lot.

**Comment by mmorel-35** [comment]
Thank you @Jeeppler , I really appreciate the compliment. This was a very interesting feature to discover and integrate.

**Pull request merged**
