### PR TITLE
Find more tempdirs

### PR DESCRIPTION
**Pull request by scop**
See individual commits for details.

### CODE REVIEW

**Comment by ccojocar** [comment]
@scop Please could you have a look, the build is failing?

**Review by ccojocar — APPROVED** [review]

**Comment by ccojocar** [comment]
@scop Please could you rebase your branch? The test should run now after upgrading ginkgo.

**Review by ccojocar — APPROVED** [review]

**Comment by scop** [comment]
Rebased.

**Comment by ccojocar** [comment]
@scop There is a test failing when the unit tests are executed second time for generating the coverage. Please could you have a look? It might be related to the existing temp files which doesn't get cleaned up after first tests execution.

**Comment by scop** [comment]
At least the latter of the two commits (which I didn't originally intend to include here but decided eventually otherwise and hastily ported over from another branch) added a test case but failed to bump the number of expected hits, that's fixed now. Not sure why it'd manifest just as a coverage failure, as it's a clear bug. Anyway should be taken care of now.

**Review by ccojocar — APPROVED** [review]

**Pull request merged**
