### PR TITLE
Update Design of HTML report

### PR DESCRIPTION
**Pull request by mmorel-35**
Update Bulma to 0.9.2 
Add Highlight Js
Change Filters and badges design

@ccojocar, @bakito , please have a look on the new design.

Would there be a way to have a preview that we could discuss ?

### CODE REVIEW

**Comment by mmorel-35** [comment]
This is ready for review. I realized that highlightJS required to refresh the component after it's mounted

**Comment by mmorel-35** [comment]
Highlight has to be applied to pre code, see https://highlightjs.readthedocs.io/en/latest/api.html#highlightall, I'm going to fix this

**Comment by ccojocar** [comment]
@mmorel-35 Can you please attach a report with the new design? I would like to have a look at it before merging this pull request. Thanks!

**Comment by mmorel-35** [comment]
[index.html.txt](https://github.com/securego/gosec/files/6537466/index.html.txt)

**Review by ccojocar — APPROVED** [review]

**Pull request merged**
