### PR TITLE
Reproducible junit report

### PR DESCRIPTION
**Pull request by xpivarc**
In some cases, stable ordering or the reproducible output is needed(CI).
This PR adds additional sorting to severity sorting to ensure stable output.
Futhermore this also fix junit output which didn't respect ordering.

### CODE REVIEW

**Review by ccojocar — APPROVED** [review]
Thanks for this contribution.

**Comment by ccojocar** [comment]
@xpivarc The pull request looks good. Could you add please some tests? It seem that the test coverage had decreased. You can find more details here https://codecov.io/gh/securego/gosec/compare/868556b846eafed2980f9708077c402be36ed28f...7d0c5818d73235e5a937e27cf0b7bcb4e919126f. Thanks!

**Comment by xpivarc** [comment]
@ccojocar I added some tests. Let me know if this is sufficient or you would like to see something more specific. I also noticed that coverage reported some unrelated changes.

**Review by ccojocar — APPROVED** [review]
Thanks for adding some tests.

**Pull request merged**
